spring:
  application:
    name: eureka-server

server:
  port: 8761
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
